### ISSUE TITLE
tube.privacytools.io certificate expired

### ISSUE THREAD

**Issue by chamilad** [privacytoolsIO/services#40] opened 2021-04-14 00:13 UTC
**Service**
What service are you trying to access?
https://tube.privacytools.io

**Describe the issue**
A clear and concise description of what the issue is. Please include any error messages you see in your browser/app/etc.
Expired server certificate provided when visiting the site

**Demographics**
Your country: New Zealand
Your ISP: 

**Screenshots**
![Screen Shot 2021-04-14 at 12 10 35](https://user-images.githubusercontent.com/505989/114636250-ab162d80-9d1a-11eb-84d9-80d114c3f408.png)

**Desktop (please complete the following information):**
 - OS: MacOSx Big sur
 - Browser Firefox
 - Version 

**Additional context**

**Comment by freddy-m** [comment] 2021-04-14 10:31
We are aware of this, and are working to fix it 👍🏼

**Comment by freddy-m** [comment] 2021-04-17 11:50
The problem is now resolved, but I can't close this issue lol

**Closed as completed** 2021-04-20 23:38 UTC
Labels: downtime
